test_name: Test without creation of nonce for attester session

marks:
  - usefixtures:
      - remove_cbor
      - psa_generate_good_evidence

strict:
  - json:off

stages:
  - name: submit post request to the provisioning service successfully 
    request:
      method: POST
      url: http://{tavern.env_vars.PROVISIONING_CONTAINER_NAME}.{tavern.env_vars.VTS_PROVISIONING_NETWORK_ALIAS}:8888/endorsement-provisioning/v1/submit
      headers:
        content-type: "application/corim-unsigned+cbor; profile=http://arm.com/psa/iot/1"
      file_body: /test-vectors/provisioning/cbor/corim-full.cbor
    response:
      status_code: 200

  - name: verify as attester - creation of session resource
    request:
      method: POST
      url: 'http://{tavern.env_vars.VERIFICATION_CONTAINER_NAME}.{tavern.env_vars.VTS_VERIFICATION_NETWORK_ALIAS}:8080/challenge-response/v1/newSession?nonceSize=32'
    response:
      status_code: 201
      verify_response_with:
        function: test_utils:generate_token

  - name: verify as attester - submitting the evidence
    request:
      method: POST
      url: 'http://{tavern.env_vars.VERIFICATION_CONTAINER_NAME}.{tavern.env_vars.VTS_VERIFICATION_NETWORK_ALIAS}:8080/challenge-response/v1/1111-2222-3333'
      headers:
        content-type: application/psa-attestation-token
      file_body: /test-vectors/verification/cbor/psa-good-evidence.cbor
    response:
      # Outputs a "Could not find request resource" error
      status_code: 404