name: Automatic monthly tag with format v0.0.yyMM
on:
  schedule:
    # At 00:00 on the first day of each month
    - cron: '0 0 1 * *'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a new tag and push it
        run: |
          TAG="v0.0.$(date +%y%m)"
          git tag $TAG
          git push origin $TAG
